### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by mrtancau** [tuxity/insta-unfollower#12]
Hi Tuxity,

thank you for your work.
I'm facing this issue:

After few unfollowed users the script gives me an error.

Traceback (most recent call last):
  File "unfollow.py", line 227, in <module>
    main()
  File "unfollow.py", line 219, in main
    unfollow(user)
  File "unfollow.py", line 164, in unfollow
    response = json.loads(response.text)
  File "C:\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tuxity** [comment]
I have no problem, I think it's because Instagram restrict the amount of requests coming from your IP.
