### ISSUE TITLE
get stuck and error in unfollowing users.

### ISSUE THREAD

**Issue by mohammadkh76** [tuxity/insta-unfollower#27]
i get this error after 1 hour waiting .
Traceback (most recent call last):
  File "insta-unfollower.py", line 235, in <module>
    main()
  File "insta-unfollower.py", line 225, in main
    while unfollow(user) == False:
  File "insta-unfollower.py", line 167, in unfollow
    response = json.loads(response.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by NeutrinoBR** [comment]
same here.

Traceback (most recent call last):
  File "insta-unfollower.py", line 235, in <module>
    main()
  File "insta-unfollower.py", line 225, in main
    while unfollow(user) == False:
  File "insta-unfollower.py", line 167, in unfollow
    response = json.loads(response.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by haroot** [comment]
Same. Any fix please?

`Traceback (most recent call last):
  File "insta-unfollower.py", line 281, in <module>
    main()
  File "insta-unfollower.py", line 270, in main
    while unfollow(user) == False:
  File "insta-unfollower.py", line 176, in unfollow
    response = json.loads(response.text)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by tuxity** [comment]
Unfortunately I don’t think there is a fix possible since it’s because of Instagram. Your IP has been banned for a time.
