### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mitacheto** [tuxity/insta-unfollower#29]
C:\Users\MitakaMadafaka\Desktop\insta-unfollower-master>python insta-unfollower.py
Traceback (most recent call last):
  File "insta-unfollower.py", line 281, in <module>
    main()
  File "insta-unfollower.py", line 208, in main
    is_logged = login()
  File "insta-unfollower.py", line 47, in login
    'X-CSRFToken': reponse.cookies['csrftoken']
  File "C:\Users\MitakaMadafaka\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\MitakaMadafaka\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by jack75015** [comment]
Hey
I got the same error too..
If someone found a solution to pass over this stucky problem... :)

**Comment by unoexperto** [comment]
@tuxity I think error message fix is addressing symptom, but not the root cause. I see that request to / no longer responds with set cookie header for `csrftoken`. After authenticating in the browser I see that first time `x-csrftoken` is set in response to https://www.instagram.com/qp/batch_fetch_web/.

So it's not possible to authenticate with current version of insta-unfollower. Would you like me to create separate issue for this ?
