### ISSUE TITLE
Fails after trying to unfollow

### ISSUE THREAD

**Issue by dmendez1** [tuxity/insta-unfollower#32]
Begin to unfollow users...
Traceback (most recent call last):
  File "insta-unfollower.py", line 280, in <module>
    main()
  File "insta-unfollower.py", line 269, in main
    while unfollow(user) == False:
  File "insta-unfollower.py", line 175, in unfollow
    response = json.loads(response.text)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AlexZm7** [comment]
Traceback (most recent call last):
  File "insta-unfollower.py", line 281, in <module>
    main()
  File "insta-unfollower.py", line 208, in main
    is_logged = login()
  File "insta-unfollower.py", line 47, in login
    'X-CSRFToken': reponse.cookies['csrftoken']
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by tuxity** [comment]
Related to #29
