### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Zethrus** [tuxity/insta-unfollower#40]
Tried to run this script with both the Docker version as well as without Docker and I am having no luck.

Without Docker, I am getting this error:
```
Traceback (most recent call last):
  File "insta-unfollower.py", line 288, in <module>
    main()
  File "insta-unfollower.py", line 213, in main
    is_logged = login()
  File "insta-unfollower.py", line 63, in login
    response_data = json.loads(response.text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any idea?

**Comment by m1stik** [comment]
Same here

**Comment by junaidihalim** [comment]
I want to confirm the same issue.

Python version 3.6.9
Requests version 2.24.0

**Comment by eduardobarbiero** [comment]
try to see:

https://github.com/tuxity/insta-unfollower/pull/38/commits/06121d099d98ce696e959ffe83c93fac851ac3d9

**Comment by tuxity** [comment]
Hello,

It should be fixed since a while now. I'm closing the issue, don't hesitate to comment if needed.
