### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by parrabram** [tuxity/insta-unfollower#49]
Begin to unfollow users...
Traceback (most recent call last):
  File "insta-unfollower.py", line 301, in <module>
    main()
  File "insta-unfollower.py", line 290, in main
    while unfollow(user) == False:
  File "insta-unfollower.py", line 195, in unfollow
    response = json.loads(response.text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

PLEASE HELP

**Comment by quadroli** [comment]
@parrabram i to was facing the exact same issue, but i found [this repo](https://github.com/ricardojoserf/instagram-followers-bot) worked for me

**Comment by parrabram** [comment]
> @parrabram i to enfrentaba exactamente el mismo problema, pero encontré que [este repositorio](https://github.com/ricardojoserf/instagram-followers-bot) funcionó para mí

thank you very much for the recommendation, I will check it out right now

**Comment by tuxity** [comment]
You can try again, I have some changes

**Comment by Zethrus** [comment]
I'm getting this when using the script with both docker and non-docker Python 3.7.
Error below is from docker version:
`Traceback (most recent call last):
  File "insta-unfollower.py", line 282, in <module>
    main()
  File "insta-unfollower.py", line 275, in main
    while unfollow(user) == False:
  File "insta-unfollower.py", line 190, in unfollow
    response = json.loads(response.text)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by tuxity** [comment]
I can't reproduce.

Try to add `print(response.text)` at line 190 just before `response = json.loads(response.text)`

**Comment by Zethrus** [comment]
> print(response.text)

With that added before the response variables, here's the error: https://pastebin.com/LZBW14mG

**Comment by tuxity** [comment]
I think somehow you are not considered as logged in, did you remove files in cache directory ?

**Comment by Zethrus** [comment]
> I think somehow you are not considered as logged in, did you remove files in cache directory ?
Strange, all I did was clear the cache directory before running the script. If I wasn't considered logged in, then how would it unfollow some of the other accounts. For the first few it seems to work fine.

Would it have anything to do with the cache directory being located in the same directory as the cloned git repo? It's located under ~/insta-unfollower/cache

**Comment by gab1992** [comment]
Python 3.8.6 same error

It also happens the same on the other repo https://github.com/ricardojoserf/instagram-followers-bot
with his program
Exact same error, happen after also 15 unfollowing

Must have to do with instagram blocking unfollowing after 15 unfollow

**Comment by tuxity** [comment]
Oh it's only doing after few unfollows ? I thought it was on the first.

Then yes, it must be some kind of limit. I will more tests this weekend.

**Comment by Zethrus** [comment]
> Oh it's only doing after few unfollows ? I thought it was on the first.
> 
> Then yes, it must be some kind of limit. I will more tests this weekend.

Is there any way I could edit the script to add a time to wait between each unfollow to possibly fix this? 
I don't mind running the script in a screen session oon a server all day if thats the case.

**Comment by tuxity** [comment]
Your account is a new account ? When googling instangram unfollow limits I found this:

```
    15 unfollows day 1
    20 unfollows day 2
    25 unfollows day 3
    30 unfollows day 4
    35 unfollows day 5
    40 unfollows day 6
    45 unfollows day 7
… and so on until I reach 150 unfollows/day
```


```
    1 unfollows/hr day 1
    2 unfollows/hr day 2
    2-3 unfollows/hr day 3
    3 unfollows/hr day 4
    3-4 unfollows/hr day 5
    4 unfollows/hr day 6
    4-5 unfollows/hr day 7

… and so forth until I reach a maximum of 13 unfollows per hour
```

**Comment by Zethrus** [comment]
> Your account is a new account ? When googling instangram unfollow limits I found this:
Not new at all, 5+ years old. 2300+ following that I have to unfollow.

**Comment by gab1992** [comment]
I ran it again, 17 unfollowed, and then the `File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

Account not new either, I think I have it since 2 years ago.

**Comment by gab1992** [comment]
Could the error come from account that are private and ask if you are sure you want to unfollow them ?

**Comment by netayamin** [comment]
anyone solved this?

**Comment by netayamin** [comment]
the error comes up whenever a 403 response received and the message of this response is 
"Please wait a few minutes before you try again." 

I was able to solve this using the following code in the unfollow func: 
      if response.status_code == 403 : 
        return False
        
and with this code added to the main func: 
         if unfollow(user) == False : 
                print("trying to unfollow %s again in 1 min" %(user["username"]))
                sleep(60)
                unfollow(user)

and by increasing the wait time between each unfollow request I believe this error shouldn't appear at all

**Comment by Zethrus** [comment]
> the error comes up whenever a 429 response received and the message of this response is
> "Please wait a few minutes before you try again."
> 
> I was able to partly solve this using the following code in the unfollow func:
> 
> ```
>  if response.status_code == 429 : 
>         return False
> ```
> 
> and with this code added to the main func so it will now loop the function instead of throwing an error:
> 
> ```
>  if unfollow(user) == False : 
>                print("trying to unfollow %s again in 1 min" %(user["username"]))
>                sleep(60)
>                unfollow(user)
> ```
> 
> **and by increasing the wait time between each unfollow request I believe this error shouldn't appear at all**

Could you post the fixed file on gist? I'm not exactly fluent in Python so editing the file is leading me to all sorts of errors.

**Comment by R3test678** [comment]
Not even getting to unfollow one user,  getting error

Traceback (most recent call last):
  File "insta-unfollower.py", line 282, in <module>
    main()
  File "insta-unfollower.py", line 275, in main
    while unfollow(user) == False:
  File "insta-unfollower.py", line 190, in unfollow
    response = json.loads(response.text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
