### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rjworks** [tuxity/insta-unfollower#57]
While unfollowing people
```
Traceback (most recent call last):
  File "insta-unfollower.py", line 282, in <module>
    main()
  File "insta-unfollower.py", line 275, in main
    while unfollow(user) == False:
  File "insta-unfollower.py", line 190, in unfollow
    response = json.loads(response.text)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by neofeo** [comment]
also
