### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by jeffreyouni** [tuxity/insta-unfollower#60]
Hi there,
How are you?
I am getting this error.
Could you have a look?
Traceback (most recent call last):
  File "C:\Users\zz\Downloads\Compressed\insta-unfollower-master\insta-unfollower.py", line 289, in <module>
    main()
  File "C:\Users\zz\Downloads\Compressed\insta-unfollower-master\insta-unfollower.py", line 222, in main
    connected_user = get_user_profile(credentials.username)
  File "C:\Users\zz\Downloads\Compressed\insta-unfollower-master\insta-unfollower.py", line 90, in get_user_profile
    response = json.loads(extract.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by xceejay** [comment]
Same for me, have you been able to fix this?

**Comment by Alb93** [comment]
Check this out https://github.com/tuxity/insta-unfollower/pull/69
