### ISSUE TITLE
KeyError: 'authenticated'

### ISSUE THREAD

**Issue by 89z** [tuxity/insta-unfollower#62]
Using this command:

~~~
python insta-unfollower.py srpen6 PASSWORD
~~~

I get this result:

~~~
Traceback (most recent call last):
  File "D:\Desktop\insta-unfollower-master\insta-unfollower.py", line 289, in <module>
    main()
  File "D:\Desktop\insta-unfollower-master\insta-unfollower.py", line 213, in main
    is_logged = login()
  File "D:\Desktop\insta-unfollower-master\insta-unfollower.py", line 83, in login
    return response_data['authenticated']
KeyError: 'authenticated'
~~~

**Comment by 89z** [comment]
Closing this in favor of my own package:

https://github.com/89z/mech/tree/master/instagram
