### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

### ISSUE THREAD

**Issue by narzero** [tuxity/insta-unfollower#64]
Just run this with Docker via

```
docker pull tuxity/insta-unfollower:latest
docker run -d -v $(pwd)/cache:/usr/src/insta-unfollower/cache --env INSTA_USERNAME=myusername --env INSTA_PASSWORD=mypassword tuxity/insta-unfollower:latest
```

After about 20 unfollows I keep getting this error:
```
Traceback (most recent call last):
  File "/usr/src/insta-unfollower/insta-unfollower.py", line 282, in <module>
    main()
  File "/usr/src/insta-unfollower/insta-unfollower.py", line 275, in main
    while unfollow(user) == False:
  File "/usr/src/insta-unfollower/insta-unfollower.py", line 190, in unfollow
    response = json.loads(response.text)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

Might be the same as #49 but there's no solution yet in the latest Docker image I pulled.

**Comment by tuxity** [comment]
I have updated the image, you can try again. 
Docker Hub changed pricing plans and automated builds are parts of a paid plans now.

**Comment by narzero** [comment]
@tuxity thanks for the quick reply.

When pulling the latest image and running it on my MacBook Pro (Retina, 13-inch, Early 2015 / 2,7 GHz Dual-Core Intel Core i5) I get the following error:

```
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
```

And it stops.

**Comment by narzero** [comment]
@tuxity thanks! will test tomorrow

**Comment by tuxity** [comment]
I have updated docker image to amd64 arch, I was building on my m1 Macbook Pro sorry. I will fix later the automated docker build
