### ISSUE TITLE
KeyError: "name='csrftoken', domain=None, path=None" Error

### ISSUE THREAD

**Issue by slinkyone** [tuxity/insta-unfollower#70]
Traceback (most recent call last):

  File "/usr/src/insta-unfollower/insta-unfollower.py", line 282, in <module>

    main()

  File "/usr/src/insta-unfollower/insta-unfollower.py", line 273, in main

    while unfollow(user) == False:

  File "/usr/src/insta-unfollower/insta-unfollower.py", line 182, in unfollow

    'x-csrftoken': response.cookies['csrftoken']

  File "/usr/local/lib/python3.10/site-packages/requests/cookies.py", line 334, in __getitem__

    return self._find_no_duplicates(name)

  File "/usr/local/lib/python3.10/site-packages/requests/cookies.py", line 413, in _find_no_duplicates

    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")

KeyError: "name='csrftoken', domain=None, path=None"

**Comment by HunterFuzzo** [comment]
same problem

**Comment by satish-mm** [comment]
Thanks @ tannerkrewson. Your fix is working fine.
