### ISSUE TITLE
Program closing

### ISSUE THREAD

**Issue by Murqd101** [tuxity/insta-unfollower#78]
It starts how it is supposed to grab my list of people im following that are following back, then starts the unfollowing of users process. It then closes the whole program as it starts and does nothing.

**Comment by manojpgoswamigit** [comment]
Script fails as soon as it begins to unfollow users.

```
Begin to unfollow users...
Unfollowing bigboy...
Traceback (most recent call last):
  File "C:\Users\test\Desktop\insta-unfollower-main\insta-unfollower.py", line 271, in <module>
    main()
  File "C:\Users\test\Desktop\insta-unfollower-main\insta-unfollower.py", line 262, in main
    while unfollow(user) == False:
  File "C:\Users\test\Desktop\insta-unfollower-main\insta-unfollower.py", line 157, in unfollow
    response = session.get(profile_route % (instagram_url, user['username']))
TypeError: not all arguments converted during string formatting
```

**Comment by kosmosnya** [comment]
Got this error too.


fix errors:

Traceback (most recent call last):
  File "/Users/kosmosnya/Library/Mobile Documents/com~apple~CloudDocs/Work/Automation/insta-unfollower-main/insta-unfollower.py", line 271, in <module>
    main()
  File "/Users/kosmosnya/Library/Mobile Documents/com~apple~CloudDocs/Work/Automation/insta-unfollower-main/insta-unfollower.py", line 262, in main
    while unfollow(user) == False:
          ^^^^^^^^^^^^^^
  File "/Users/kosmosnya/Library/Mobile Documents/com~apple~CloudDocs/Work/Automation/insta-unfollower-main/insta-unfollower.py", line 157, in unfollow
    response = session.get(profile_route % (instagram_url, user['username']))
                           ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: not all arguments converted during string formatting
