### ISSUE TITLE
error i'm getting  when launching the script

### ISSUE THREAD

**Issue by neomh** [tuxity/insta-unfollower#8]
/insta-unfollower$ USERNAME=xxxx PASSWORD=xxxxx python3 insta-unfollower.py
Traceback (most recent call last):
  File "insta-unfollower.py", line 208, in <module>
    main()
  File "insta-unfollower.py", line 172, in main
    connected_user = get_user_profile(os.environ.get('USERNAME'))
  File "insta-unfollower.py", line 64, in get_user_profile
    response = json.loads(response.text)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

Thank you

**Comment by RaffaeleNachos** [comment]
json.loads (line 67) should "convert" a json package (the one returned by instagram) to a python dictionary.
So, maybe instagram have changed the sintax of the informations in the package.
I'm woking on it but when it used to start this script didin't work... 
I would like to help but most code isn't commented...

**Comment by tuxity** [comment]
More Instagram changes have been made.
You can see one thread here https://stackoverflow.com/questions/49265339/instagram-a-1-url-doesnt-allow-max-id

I'm gonna try to adapt the script soon
