### ISSUE TITLE
Arguments not converted during string formatting.

### ISSUE THREAD

**Issue by DannyTaki** [tuxity/insta-unfollower#86]
Ran into an issue running in Docker setup.

2024-03-07 21:43:50 Unfollowing marco_serva...
2024-03-07 21:43:50 Traceback (most recent call last):
2024-03-07 21:43:50   File "/usr/src/insta-unfollower/insta-unfollower.py", line 271, in <module>
2024-03-07 21:43:50     main()
2024-03-07 21:43:50   File "/usr/src/insta-unfollower/insta-unfollower.py", line 262, in main
2024-03-07 21:43:50     while unfollow(user) == False:
2024-03-07 21:43:50           ^^^^^^^^^^^^^^
2024-03-07 21:43:50   File "/usr/src/insta-unfollower/insta-unfollower.py", line 157, in unfollow
2024-03-07 21:43:50     response = session.get(profile_route % (instagram_url, user['username']))
2024-03-07 21:43:50                            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-03-07 21:43:50 TypeError: not all arguments converted during string formatting

**Comment by DannyTaki** [comment]
Ah figured it out their rest api isn't available anymore.
